version: '3'

services:
  nest-graphql:
    build:
      context: .
      dockerfile: Dockerfile
    image: nest-graphql
    container_name: nest-graphql
    restart: always
    ports: 
      - 5000:3000
    